command = tweet-command
        | wall-command
        | follow-command
        | read-command

tweet-command	= username <whitespace> <"->"> <whitespace> freetext
wall-command	= username <whitespace> <"wall">
follow-command	= username <whitespace> <"follows"> <whitespace> username
read-command	= username

whitespace = #"\s*"
username = #"\w+"
freetext = #".*"
